export const KEYWORDS_RESPONSE_MOCKUP = {
  keywords: [
    {
      keyword: 'software',
      search_volume: 368000,
      cpc: 3.99,
      competition: 'LOW',
      competition_index: 8,
      low_top_of_page_bid: 1.06,
      high_top_of_page_bid: 5.36,
    },
    {
      keyword: 'developer',
      search_volume: 33100,
      cpc: 11.31,
      competition: 'LOW',
      competition_index: 9,
      low_top_of_page_bid: 2.38,
      high_top_of_page_bid: 11.55,
    },
    {
      keyword: 'react',
      search_volume: 60500,
      cpc: 7.22,
      competition: 'LOW',
      competition_index: 1,
      low_top_of_page_bid: 1.85,
      high_top_of_page_bid: 6.23,
    },
    {
      keyword: 'native',
      search_volume: 110000,
      cpc: 1.26,
      competition: 'HIGH',
      competition_index: 100,
      low_top_of_page_bid: 0.28,
      high_top_of_page_bid: 1.89,
    },
    {
      keyword: 'software',
      search_volume: 368000,
      cpc: 3.99,
      competition: 'LOW',
      competition_index: 8,
      low_top_of_page_bid: 1.06,
      high_top_of_page_bid: 5.36,
    },
    {
      keyword: 'developer',
      search_volume: 33100,
      cpc: 11.31,
      competition: 'LOW',
      competition_index: 9,
      low_top_of_page_bid: 2.38,
      high_top_of_page_bid: 11.55,
    },
    {
      keyword: 'react',
      search_volume: 60500,
      cpc: 7.22,
      competition: 'LOW',
      competition_index: 1,
      low_top_of_page_bid: 1.85,
      high_top_of_page_bid: 6.23,
    },
    {
      keyword: 'native',
      search_volume: 110000,
      cpc: 1.26,
      competition: 'HIGH',
      competition_index: 100,
      low_top_of_page_bid: 0.28,
      high_top_of_page_bid: 1.89,
    },
  ],
  totalCount: 4,
};
